### ISSUE TITLE
Text Alignment to right

### ISSUE THREAD

**Issue by rajsuvariya** [TomRoush/PdfBox-Android#101]
```

        contentStream.beginText();
        contentStream.setFont(font, 10);
        contentStream.setLeading(12f);
        contentStream.newLineAtOffset(myPage.getMarginLeft(), 700);

        String temp="";

        String[] sentences = data.split("\n");
        for (String sentence : sentences){
            ArrayList<String> lines = wrap(sentence, font, myPage);
            for (String line : lines){
                contentStream.showText(line);
                contentStream.newLine();
            }
        }
        contentStream.endText();

```

I want to align the text to right. I have lot of strings in ArrayList lines. How can I align it to right?

**Comment by TomRoush** [comment]
There's no method that causes the text to align to the right. A similar effect can be achieved with something like [this code.](http://stackoverflow.com/questions/24004539/right-alignment-text-in-pdfbox) You will need to shift each line over so that they align to the right by computing the length of each line.
