### ISSUE TITLE
ANDROID: encrypting a pdf is not working...

### ISSUE THREAD

**Issue by HowardSchmaeu** [TomRoush/PdfBox-Android#102]
i've tried to encrypt a pdf like described [here](https://pdfbox.apache.org/2.0/cookbook/encryption.html#) ... but it does not work. 
If i set the keyLength = 256 i get in foxit a password dialog but the key "12345" is not working. If i open this file in Adobe i get a error that the File is corrupt. I also tried the other 2 keyLength Values but THEN the file is not encrypted.

did i missed something or is encryption not working with your lib??

Thx Howard

**Comment by TomRoush** [comment]
[StackOverflow question for reference.](http://stackoverflow.com/questions/42551122/encrypting-a-pdf-is-not-working-with-pdfbox-android) Since this is based on v1.8, 256 key length isn't supported.
If you're trying to protect the file from being read without a password, you need to put a password in the second argument of the StandardProtectionPolicy constructor. If you're trying to prevent something else, like editing, then you need to modify the AccessPermission to set the permissions.

**Comment by HowardSchmaeu** [comment]
Ahhh you found my Question on Stackoverflow too :+1:  :-)

Okay my Fault... i THOUGHT i use one of the other keyLength Values... but NOW if i've tried it again... it works at the end. Thanx for helping me out
