### ISSUE TITLE
Questions about AcroForm support, Xamarin and Visual Studio

### ISSUE THREAD

**Issue by Alex-DE-74** [TomRoush/PdfBox-Android#140]
Hello Tom,

nice and important work you done!

I'm very new in Android development (but done Java bevore) and would like to know:
 - If and how it is possible to use this library together with Visual Studio and Xamarin?
 - Is here any good samples how to construct a simply PDF Viewer with zoom in/out and page up/down?
 - Is there any compiled libraries for specific minimum android version, so that it can be simply embedden in such a project?
 - How well the AcroForms are _actually_ supported with folllowing subtopics
     -- any particular implementation, i.e. only for textfields?
     -- how well drawing of AcroForms with(out) annotation widgets is supported?
     -- any support for all or partucular types of fields to 'manuall' fill in (like inside Acrobat Reader)?
 - In respect to AcroForms question abouve, how complex / long time it would be taken realistically for "any new in android arbitrary but experienced as developer" person in order to implement very basic rudimentary functionality (without lots of fonts/colors, etc) for filling of AcroForms by an user and read-out by an program? I know, such a question is "cloudy", but I hope, you understand my motivation.

Specifically for last question I will try to explain, what is my assumption about implementation (i.e.text field):
 - Important information about AcroForm fields are already passend and can by "simply" queried
 - Basic drawing of empty or/and filled field is already supported
 - All that is done on image (and image is currenly presented in a view) or directly in a view
 - User press in (click) on a view, the click-point is analysed and if it is "inside any field coordinate" an android widget ic constructed dynamically on a view and got focus
 - After user is entered a value (hit enter or some button outside PDF page), this value would be applied as field value, android widget is dynamically removed and PDF page would be rendered again.
 - Is all that realistic to implement in a very short time?

Many thanks for considering my questions!

Alex

**Comment by TomRoush** [comment]
- I don't have any experience doing Android development with Xamarin / Visual Studio. It should be the same as using any other Java library if you know how to do that. [I don't know if this plugin is what you need, but it says that it can import Java Gradle dependencies into your Xamarin project.](https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings)
 - There aren't any PDF viewer samples that I know of for this library. You could look at other viewers or how to do something similar with Android Bitmaps, since that what the PDF pages are rendered as.
 - [The latest version of the library is available here.](https://bintray.com/birdbrain2/PdfBox-Android/PdfBox-Android/_latestVersion) You can import it via Gradle or download the aar file it that is easier to use in Xamarin. All functionality is available at API 19, but only a couple a lines use API 19 (I don't remember which though), so you could go lower it those functions aren't used.
 - Acroforms should be almost completely implemented and bug-free.
     -- All of the types of form fields are supported
     -- Most of the form fields should render properly. I've have to check, but signature fields and possibly list boxes might not be rendering correctly. 
     -- I'm assuming for this point you mean clicking on a fields and typing in a value? This library purely does the function calls, so you'd have to implement this yourself.

 - It's hard to give an estimate, but I don't think it should be too bad if you're only looking to start with something basic. If you haven't already, take a look at the functions in the [samples project](https://github.com/TomRoush/PdfBox-Android/blob/master/sample/src/main/java/com/tom_roush/pdfbox/sample/MainActivity.java) and [here](https://bricolsoftconsulting.com/working-with-pdf-forms-on-android/). These are in Java, but should give you and idea of how to do a lot of the things you need to do.
 -- Information about AcroFroms is parsed when you load in a PDF.
 -- Forms and thier data are drawn when you render the page.
 -- Rendering the page produces a Bitmap, which can be drawn in an ImageView (the rendering sample does this).
 -- This is the part that would require the most work. The location of the form elements are available, but you would need to convert the PDF coordinates to the screen coordinates and overlay a TextView over the field's location. If you're trying to throw together a quick prototype, I would skip this step for now.
 -- After setting the new value of the field, you would need to call render again and assign the new Bitmap to the ImageView. Shouldn't be bad.
 -- Depends on your definition of a short time, but if you simplify the features you need, the basics shouldn't take too long to work out. As I mentioned before, if you're looking to be quick, putting the TextView in its actual location is probably the most difficult part of what you're trying to do.

Best of luck and hope that this helps.
