### ISSUE TITLE
Pdf search and highlight

### ISSUE THREAD

**Issue by erkangozukucuk** [TomRoush/PdfBox-Android#144]
Hi,
How to use xml file that generated generateXMLHighlight method in PdfHighlighter.java class?

Thanks for advices.

**Comment by TomRoush** [comment]
The PDFHighlighter class is just an example that demonstrates extending the TextStripper class. [The important part is right here.](https://github.com/apache/pdfbox/blob/f4fe6a165ebfd5e227b72024f89197cc92c35428/examples/src/main/java/org/apache/pdfbox/examples/util/PDFHighlighter.java#L124) That line writes the location and page number to a file. Instead of `highlighterOutput.write()`, you can add whatever functionality you need.

**Comment by rami-alloush** [comment]
Has anyone implemented full "search" example?
Please share, thanks :)
