### ISSUE TITLE
Android 8.0

### ISSUE THREAD

**Issue by YunLai0429** [TomRoush/PdfBox-Android#160]
It fails when I create the pdf on Android version 8.0
Let me know the reason.

**Comment by TomRoush** [comment]
Can you share the code and/or the error you get?

**Comment by YunLai0429** [comment]
http://crashes.to/s/f2184f14abd
http://crashes.to/s/d60f5127104
http://crashes.to/s/d44d1c2c94b

**Comment by TomRoush** [comment]
I haven't been able to reproduce these on an 8.0 device, but I have some ideas on what could be happening. The OutOfMemoryError is probably the same issue as #131. Bitmap memory management is currently fairly inefficient. The No space left on device and FileNotFoundException I suspect are not caused by an issue in the library, but by the device not having enough space or a folder not existing. It could also be a permission problem, especially on API >= 23.
