### ISSUE TITLE
The library's resource loader initialization

### ISSUE THREAD

**Issue by dbeqiraj** [TomRoush/PdfBox-Android#178]
I just tried to add this line:
`PDFBoxResourceLoader.init(getApplicationContext());`
 in my `Application `class, **@onCreate method**, and the code doesn't give any error.

If I do multiple calls to PDFBox in different classes, it would be a better practice to call the line above just once.

Questions:
Is this approach recommended?
Does it have any potential drawback?

**Comment by TomRoush** [comment]
With `getApplicationContext()`, you only need to call `init` once per application, no matter how many classes you have that use PDFBox. There's no harm in calling `init` multiple times, but any calls after the first one won't do anything since initialization has already occurred. Does that answer your questions?

**Comment by dbeqiraj** [comment]
@TomRoush It's all clear. Thank you.
