### ISSUE TITLE
Create a table

### ISSUE THREAD

**Issue by Jerome2212** [TomRoush/PdfBox-Android#197]
Hi,

First of all, big thanks for creating this lib.

I am trying to use it to create a table report in a A4 format. But, do anyone know a way to do it(create a table and set the format to A4)? 

Thanks in advance!

**Comment by THausherr** [comment]
See the javadoc for the `PDPage` constructor. Tables must be created low level, i.e. draw appropriate lines. There are tools on top of PDFBox, e.g. boxable, but I don't know if that works on Android.

**Comment by Jerome2212** [comment]
Thanks for replying! Tool on top of PdfBox are unfortunately not available on android due to non access to java.awt (something like this) . So I should do it from low level but I have no clue on how to do it , I hope to find a solution!

**Comment by THausherr** [comment]
I looked and yes, they use awt :-(  Not much, but it would still be extra work.

To see how to use PDFBox for PDF generation, get the sources for the desktop project and look at the examples subproject.

**Comment by harikautilya** [comment]
(Redacted and removed the file here)

Hey
 i have worked on creating tables on A4 using this lib. But the source code is quite big around 1 mb to share here contact me if you need it. I have shared a sample image here

@Jerome2212

**Comment by harikautilya** [comment]
@THausherr

**Comment by THausherr** [comment]
I'm not with the android project nor with boxable, I just hang around here :-)

**Comment by harikautilya** [comment]
> This looks like a nice table, but I'm not with the android project nor with boxable, I just hang around here :-)

Sure convey the message if you can. Also, mind if I tweak your brain for one problem currently facing. I am unable to flatten pdf which causes the acro form field not to be saved into the Appearance stream (No clue what this means). Any suggestions?

**Comment by THausherr** [comment]
"which causes the acro form field not to be saved into the Appearance stream" - is this an error message you got? Or a text that somebody wrote elsewhere?

Flattening means that the PDF no longer has fields that behave like fields, i.e. you can't edit, nor read them with the acroform API. Technically, the appearance stream of the fields is converted into "pure" form XObjects (despite the name, this has nothing to do with "forms", it's just nested elements with a PDF content stream, resources etc), and these are invoked by the page content stream.

I don't know if flattening is implemented in the android project. The desktop project has it, but it took a long time to work properly, there were bugs that sometimes fields became invisible, or appeared at the wrong place.

To see if this works on Android, have a look at the file "PDAcroFormFlattenTest.java" in the desktop project, that one flattens 16 different files. (Note that the tests are inactive, a comparison must be made manually because there are often very slight visual differences)

**Comment by harikautilya** [comment]
mysterious text somebody wrote on the web.
Flattening is not yet implemented in the android project. Will check that file if I can find any clue for a workaround
Currently, I have created acro-form fields using pdfbox. But when I try to retrieve the bitmap using PDF render of android. The fields are no longer visible. Hence I am looking to flatten the PDF file

**Comment by THausherr** [comment]
Either the appearances streams (that is the actual display of the value) were not / wrongly generated when setting the field value, or there is a bug in displaying these appearance streams. If you can share a file I'll tell you which one it is.

**Comment by harikautilya** [comment]
(Redacted and removed the file here)
Here is the file. Please let me know. Thank you for your extended help
@THausherr

**Comment by THausherr** [comment]
Oh that one is tricky. It has /NeedAppearances set to true, which means that the viewer should generate appearances.

The field "name_of_facility" has an almost empty apearance stream, there is only "q Q" and an empty BBox. PDFBox for desktop displays nothing.

I tried to regenerate the appearances with pdfbox for desktop (`doc.getDocumentCatalog().getAcroForm().refreshAppearances();` ) and got an IOException because of a missing font. The default appearance string of the fields has "/Helvetica", but the default resources doesn't have that font (only "Helv").

**Comment by THausherr** [comment]
I tried add this font, but still nothing displayed. Reason this time: the fields all have an empty BBox in their appearance streams.

I then deleted the appearance of all text fields:
```
for (PDField field : doc.getDocumentCatalog().getAcroForm().getFieldTree())
{
    if (field instanceof PDVariableText)
    {
        for (PDAnnotationWidget widget : field.getWidgets())
        {
            widget.setAppearance(null);
        }
    }
}
doc.getDocumentCatalog().getAcroForm().refreshAppearances();

```
and here are the results:
[refreshed2.pdf](https://github.com/TomRoush/PdfBox-Android/files/3541955/refreshed2.pdf)
[refreshed-flattened.pdf](https://github.com/TomRoush/PdfBox-Android/files/3541957/refreshed-flattened.pdf)

**Comment by harikautilya** [comment]
Okie let me try that sounds like a interesting approach. I shall update you further soon. Need to modify few things before i try this

**Comment by harikautilya** [comment]
The use case is kinda like .....after filling the pdf using Pdfbox. I am trying to retrieve bitmap using the PDFrender of the android library...in which the text field go vanish along with tick boxes.


If I use the PDFRenderer of Pdfbox, I get full black pages. This is the method I used to directly getting the bitmap

renderer.renderImage(index)

**Comment by THausherr** [comment]
See my comment from 2 days ago, the text fields didn't have a proper appearance stream. Maybe PDFBox for Android doesn't support this. Try rendering the two files I attached. If these can be rendered on Android, then a solution would be to create the PDF files on the server side with Apache PDFBox.

**Comment by harikautilya** [comment]
finally found a work around.....After writing your code snippet by adding getDefaultResources. I have rendered using PDfium lib. It worked !!!!!. Thanks a lot for you @THausherr . Please let know if need any help from my side anytime.

**Comment by THausherr** [comment]
You already helped by sharing the file, it allowed me to create 3 issues in the Apache PDFBox project and fix 2 of them:
https://issues.apache.org/jira/browse/PDFBOX-4636
https://issues.apache.org/jira/browse/PDFBOX-4637
https://issues.apache.org/jira/browse/PDFBOX-4638

This issue here seems to have drifted off topic somewhat, and the original topic has been answered, so you might want to close it.

**Comment by harikautilya** [comment]
Sure. Thank you. Happy i was helpful.

@TomRoush please close this issue

**Comment by daminimehra28** [comment]
@harikautilya I need your help for table generation pdf.can you please share your contact details.

**Comment by harikautilya** [comment]
@daminimehra28 Sure harikautilya@gmail.com... drop me a mail will share contact info there..not a good idea to share contact info on GitHub issues :P

**Comment by sw-tt-kushanshah** [comment]
@harikautilya  @THausherr  can anyone of you please share code of table format PDF shown in above thread? 

Thanks in advance.
