### ISSUE TITLE
Long class load times

### ISSUE THREAD

**Issue by AedonEtLIRA** [TomRoush/PdfBox-Android#32]
When I first boot up the library to generate a PDF, I'm getting really long (30 seconds) just to load the library to the point where I can start generating PDFs. I went through the source and I think the problem is that class such as ExternalFonts and GlyphList are loading resources from disk when the class is loaded. Is there a way that we can shift this into a static initialization method or document that the static loading is occurring?

**Comment by Birdbrain2** [comment]
I'll run it through the profiler and see what has the highest impact. At the very least I can add so log lines so you'll know when it's entering and leaving the long methods.

**Comment by ultimatecollections** [comment]
I have the same problem. When I first launch the android app and try to use the library, it takes a lot of time (approx. 30 seconds). Could you try to fix it ? Otherwise this is a great library and one I'd recommand once this problem is fixed.

**Comment by estiukamobi** [comment]
I have faced the same problem I have found a workaround but I have had to make some code changes. Loading the resource using the classLoader appears to be really slow, so I have moved them to the assets folder and created a class to load them. The drawback is that I need to initialize the class before doing anything else as it needs an Android Context.

<pre><code>
public class PDFBoxResourceLoader {

    private static Context CONTEXT = null;
    private static AssetManager ASSET_MANAGER = null;

    public static void init(Context context){
        if(CONTEXT == null) {
            CONTEXT = context.getApplicationContext();
            ASSET_MANAGER = CONTEXT.getAssets();
        }
    }

    public static InputStream getStream(String path) throws IOException {
        return ASSET_MANAGER.open(path);
    }



}
</code></pre>

Then I have replaced the classLoader calls by calls to PDFBoxResourceLoader.getStream 
<pre><code>
String cffName = "org/apache/pdfbox/resources/otf/AdobeBlank.otf";
/*url = ExternalFonts.class.getClassLoader().getResource(cffName);
if (url == null)
{
	throw new IOException("Error loading resource: " + ttfName);
}
InputStream cffStream = url.openStream();*/
InputStream cffStream = PDFBoxResourceLoader.getStream(cffName);
</code></pre>

It could be more elegant but I was a bit in the rush.

**Comment by ultimatecollections** [comment]
Thanks for your answer!

I will try this solution.

Stéphane
Le 12 mai 2015 17:14, "Jonathan Akuitse" <notifications@github.com> a
écrit :

**Comment by pyraego** [comment]
Thank you for the proposed fix.

Do you move the .otf file to your local project assets? Or create an assets folder in the PDFBox project?

This is the error I am getting:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream android.content.res.AssetManager.open(java.lang.String)' on a null object reference
            at org.apache.pdfbox.pdmodel.font.PDFBoxResourceLoader.getStream(PDFBoxResourceLoader.java:25)
            at org.apache.pdfbox.pdmodel.font.ExternalFonts.<clinit>(ExternalFonts.java:69)
            at org.apache.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:92)
            at org.apache.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:53)
            at myapp.results.fragment_results.onOptionsItemSelected(fragment_results.java:379)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1608)
            at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2012)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:378)
            at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:244)
            at android.support.v7.app.ActionBarActivityDelegateICS.onMenuItemSelected(ActionBarActivityDelegateICS.java:164)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:130)
            at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onMenuItemSelected(ActionBarActivityDelegateICS.java:308)
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1184)
            at

**Comment by estiukamobi** [comment]
I have create an assets folder in the PDFBox project, yes and I have kept the folder hierarchy of the resources folder

My bad, I forgot to mention, you will need to build a AAR file instead of the JAR otherwise the resources won't be included. In my case, I have been a bit more radical and I have included the whole project as a new module.

**Comment by pyraego** [comment]
Initalizing the PDFBoxResourceLoader class solved the issue of the null AssetManager. 

This getting a file not found exception. I have the files in place. 
     Caused by: java.io.FileNotFoundException: org/apache/pdfbox/resources/assets/LiberationSans-Regular.ttf

![screen shot 2015-05-12 at 1 13 47 pm](https://cloud.githubusercontent.com/assets/1516560/7593773/824cca50-f8aa-11e4-9497-a8ee49b5b0cd.png)

	try
		{
			// ttf
			String ttfName = "org/apache/pdfbox/resources/assets/LiberationSans-Regular.ttf";
			InputStream ttfStream = PDFBoxResourceLoader.getStream(ttfName);
			TTFParser ttfParser = new TTFParser();
			ttfFallbackFont = ttfParser.parse(ttfStream);


			// cff
			String cffName = "org/apache/pdfbox/resources/assets/AdobeBlank.otf";
			InputStream cffStream = PDFBoxResourceLoader.getStream(cffName);
			byte[] bytes = IOUtils.toByteArray(cffStream);
			CFFParser cffParser = new CFFParser();
			cidFallbackFont = (CFFCIDFont)cffParser.parse(bytes).get(0);
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}

**Comment by estiukamobi** [comment]
In the build.gradle of your app project, you need to add a dependency to either the PdfBox-Android AAR files or to add the Pdfbox-Android project as a module. Using the JAR file will not work because Android resources are not embedded in JARs.

**Comment by pyraego** [comment]
@estiukamobi Thats how I have it setup. I included the PDFBox-Android project as a module and added this line to my grade file

    compile project(':PdfBox-Android')

**Comment by Birdbrain2** [comment]
I haven't been able to work out a better method than this yet. I'll be pushing these changes sometime today or tomorrow. estiukamobi, thanks for your help.

**Comment by pyraego** [comment]
I will try it out once you push the changes @Birdbrain2. Thanks @estiukamobi for the work around.

**Comment by Birdbrain2** [comment]
Changes have been pushed. You'll want to put ``` PDFBoxResourceLoader.init(getApplicationContext());``` somewhere in your code before you start calling PDFBox methods to use the new implementation. If you forgot that line, you'll still be using the slow, old system, but you should get a log warning about it.

**Comment by pyraego** [comment]
Works prefect!

Thank You

**Comment by parthipanramesh** [comment]
Thank you! Now I don't to keep a private copy of this repository with the changes.

**Comment by kecsot** [comment]
So Important to call init before you use any class of this library.
