### ISSUE TITLE
Add PNG or Bitmap to PDF

### ISSUE THREAD

**Issue by SaimanTrajan** [TomRoush/PdfBox-Android#67]
Hi there,

I am trying to add a bitmap or png to pdf but I fail since solutions via awt and BufferedImage are not working with the Android sdk.
For now I use a workaround by saving the bitmap as jpeg and importing it with JPEGFactory. But this leads to a visible loss in quality, even when using compression rate of 100.
Is there a solution I have missed to see? Best way would be to insert the bitmap in the pdf directly.

**Comment by Phyambre** [comment]
Hi, I am not one of the members of the project, but I advice you to do two things. One is to check the class LosslessFactory instead of JPEGFactory, because I think it is the class to use when you don't want to lose quality, for example, when you use PNG images. Another is to notice that some methods of JPEGFactory receive a quality and dpi as parameters, so maybe you can play with them to get better images.

**Comment by SaimanTrajan** [comment]
Thanks for your advices.
LosslessFactory doesn't seem to be part of pdfBox for Android since it is based on PdfBox v1.8.9

**Comment by Phyambre** [comment]
What do you mean by "LosslessFactory doesn't seem to be part of pdfBox for Android since it is based on PdfBox v1.8.9"? I downloaded the PDFbox for Android from this site and I can use the class:
`import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;`
It is the same package as the JPEGFactory.

**Comment by TomRoush** [comment]
I'm assuming that you're using the jCenter version of the library, which doesn't have the LosslessFactory as that was added after the latest release. If you build the code from the repo and use that, you should be able to use the LosslessFactory as well as JPEGFactory.

**Comment by SaimanTrajan** [comment]
That was the case. Thanks to both of you for the help.

**Comment by hurzl** [comment]
LosslessFactory is extremely slow compared to JPEGFactory
