### ISSUE TITLE
Slow when creating font for the first time

### ISSUE THREAD

**Issue by gjnidea** [TomRoush/PdfBox-Android#84]
I was looking for the reason why creating a pdf is so slow and I was able to find out that creating a font,
(e.g. PDFont font = PDType1Font.HELVETICA) is very slow. In my case it takes about 10s. I might `pull request` sometime in the future for the fix of this one (if it is possible and if  I can do it), but right now I'm very busy and can't help. Just letting you know.

Btw, after creating the first pdf, the following pdf creations are fast.

**Comment by TomRoush** [comment]
This is because the first time a font is created, a lot of IO is done to initialize some of the font classes. If you haven't already, try adding `PDFBoxResourceLoader.init(getApplicationContext());` to your application somewhere before you start using PDFBox classes. This allows the library to use Android style asset loading instead of Java resource loading, which is much slower.
